name: CI
on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: go mod tidy
    - run: go vet ./...
    - run: go test ./...

